version: '3.0'
services:

  rabbitmq:
    image: rabbitmq:3.12.0-beta.6-management-alpine
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - apps/microservices/.development.env
    restart: always
    container_name: rabbitmq
    networks:
      - app

networks:
  app: