version: '3.0'
services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - apps/microservices/.development.env
    restart: always
    container_name: rabbitmq

 
  